module.exports = {
	CHANGE_GROUPACP_SUCCESS:'Cât nhật group ACP thành công',
	CHANGE_STATUS_SUCCESS:'Cât nhật stastus thành công',
	CHANGE_SPECIAL_SUCCESS:'Cât nhật special thành công',
	CHANGE_SPECIAL_MULTI_SUCCESS:'Có %d phần tử cât nhật special thành công',
	CHANGE_STATUS_MULTI_SUCCESS:'Có %d phần tử cât nhật stastus thành công',
	CHANGE_ORDERING_SUCCESS:'Cật nhật ordering thành công',
	DELETE_SUCCESS:'Xoá thành công',
	DELETE_MULTI_SUCCESS:'Xoá thành công %d phần tử',
	ADD_SUCCESS:'Thêm mới phần tử thành công',
	EDIT_SUCCESS:'Cật nhật item thành công',
	ERROR_LOGIN_EXITS:'User hoặc mật khẩu không đúng',
	ERROR_USER_EXITS:'User không tồn tại',
	GROUP_NAME_CONFIGS:'Chiều dài từ %d đến %d ký tự',
	USER_NAME_CONFIGS:'Chiều dài từ %d đến %d ký tự',
	PASS_WORD_CONFIGS:'Chiều dài từ %d đến %d ký tự',
	EMAIL_CONFIGS:'Email không hợp lệ',
	VALIDATES:{
		ERROR_NAME: 'Chiều dài từ %d đến %d ký tự',
		ERROR_ORDERING:'Phải là số nguyên lớn hơn %d và nhỏ hơn %d ',
		ERROR_STATUS:'phải được chọn',
		ERROR_CONTENT:'Chiều dài từ %d đến %d ký tự',
		ERROR_GROUPACP:'không được rỗng',
		ERROR_GROUP:'phải được chọn',
		ERROR_FILE_REQUIRE:'Vui lòng chọn file upload',
		ERROR_FILE_LIMIT:'Kích thước file không phù hợp',
		ERROR_FILE_EXTENSION:'Phần mở rộng file không hợp lệ',
		ERROR_LOGIN_USERNAME:'phải từ %d đến %d ký tự ',
	}
}